config/routes.rb
Rails.application.routes.draw do
  resources :bloggers do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogger.rb
class Blogger < ApplicationRecord
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blogger
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bloggers_controller.rb
class BloggersController < ApplicationController
  before_action :set_blogger, only: [:show, :edit, :update, :destroy]

  # GET /bloggers
  # GET /bloggers.json
  def index
    @bloggers = Blogger.all
  end

  # GET /bloggers/1
  # GET /bloggers/1.json
  def show
  end

  # GET /bloggers/new
  def new
    @blogger = Blogger.new
  end

  # GET /bloggers/1/edit
  def edit
  end

  # POST /bloggers
  # POST /bloggers.json
  def create
    @blogger = Blogger.new(blogger_params)

    respond_to do |format|
      if @blogger.save
        format.html { redirect_to @blogger, notice: 'Blogger was successfully created.' }
        format.json { render :show, status: :created, location: @blogger }
      else
        format.html { render :new }
        format.json { render json: @blogger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bloggers/1
  # PATCH/PUT /bloggers/1.json
  def update
    respond_to do |format|
      if @blogger.update(blogger_params)
        format.html { redirect_to @blogger, notice: 'Blogger was successfully updated.' }
        format.json { render :show, status: :ok, location: @blogger }
      else
        format.html { render :edit }
        format.json { render json: @blogger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bloggers/1
  # DELETE /bloggers/1.json
  def destroy
    @blogger.destroy
    respond_to do |format|
      format.html { redirect_to bloggers_url, notice: 'Blogger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogger
      @blogger = Blogger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blogger_params
      params.require(:blogger).permit(:name, :days, :content)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comments
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET bloggers/1/comments
  # GET bloggers/1/comments.json
  def index
    @comments = @blogger.comments
  end

  # GET bloggers/1/comments/1
  # GET bloggers/1/comments/1.json
  def show
  end

  # GET bloggers/1/comments/new
  # GET bloggers/1/comments/new.json
  def new
    @comment = @blogger.comments.build
  end

  # GET bloggers/1/comments/1/edit
  # GET bloggers/1/comments/1/edit.json
  def edit
  end

  # POST bloggers/1/comments
  # POST bloggers/1/comments.json
  def create
    @comment = @blogger.comments.build(comment_params)

    if @comment.save
      redirect_to([@comment.blogger, @comment], notice: 'Comment was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT bloggers/1/comments/1
  # PUT bloggers/1/comments/1.json
  def update
    if @comment.update_attributes(comment_params)
      redirect_to([@comment.blogger, @comment], notice: 'Comment was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE bloggers/1/comments/1
  # DELETE bloggers/1/comments/1.json
  def destroy
    @comment.destroy

    redirect_to blogger_comments_url(@blogger)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comments
      @blogger = Blogger.find(params[:blogger_id])
    end

    def set_comment
      @comment = @blogger.comments.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def comment_params
      params.require(:comment).permit(:name, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bloggers_helper.rb
module BloggersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/bloggers/_form.html.erb
<%= form_for(blogger) do |f| %>
  <% if blogger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blogger.errors.count, "error") %> prohibited this blogger from being saved:</h2>

      <ul>
      <% blogger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :days %>
    <%= f.text_field :days %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bloggers/edit.html.erb
<h1>Editing Blogger</h1>

<%= render 'form', blogger: @blogger %>

<%= link_to 'Show', @blogger %> |
<%= link_to 'Back', bloggers_path %>

app/views/bloggers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bloggers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Days</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bloggers.each do |blogger| %>
      <tr>
        <td><%= blogger.name %></td>
        <td><%= blogger.days %></td>
        <td><%= blogger.content %></td>
        <td><%= link_to 'Show', blogger %></td>
        <td><%= link_to 'Edit', edit_blogger_path(blogger) %></td>
        <td><%= link_to 'Destroy', blogger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blogger', new_blogger_path %>

app/views/bloggers/new.html.erb
<h1>New Blogger</h1>

<%= render 'form', blogger: @blogger %>

<%= link_to 'Back', bloggers_path %>

app/views/bloggers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @blogger.name %>
</p>

<p>
  <strong>Days:</strong>
  <%= @blogger.days %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blogger.content %>
</p>

<%= link_to 'Edit', edit_blogger_path(@blogger) %> |
<%= link_to 'Back', bloggers_path %>

app/views/comments/_form.html.erb
<%= form_for([@comment.blogger, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', [@comment.blogger, @comment] %> |
<%= link_to 'Back', blogger_comments_path(@comment.blogger) %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.name %></td>
    <td><%= comment.content %></td>
    <td><%= link_to 'Show', [comment.blogger, comment] %></td>
    <td><%= link_to 'Edit', edit_blogger_comment_path(comment.blogger, comment) %></td>
    <td><%= link_to 'Destroy', [comment.blogger, comment], :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_blogger_comment_path(params[:blogger_id]) %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', blogger_comments_path(@comment.blogger) %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @comment.name %>
</p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>


<%= link_to 'Edit', edit_blogger_comment_path(@comment.blogger, @comment) %> |
<%= link_to 'Back', blogger_comments_path(@comment.blogger) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogme</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>